### ISSUE TITLE
Automate PyPI Deployment with GitHub Actions

### ISSUE THREAD

**Issue by ojadeyemi** [mlsedigital/mplbasketball#13]
## **Description**  
Incorporate a GitHub Actions workflow to automate PyPI deployments. This ensures seamless and error-free package publishing upon creating a new release.

Using OpenID Connect (OIDC). OIDC allows secure, credential-free publishing of packages from trusted third-party services like GitHub Actions. [READ MORE HERE](https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-pypi)

## **Reference**  
Here's an [example workflow](https://github.com/ojadeyemi/usports-basketball/blob/main/.github/workflows/python-publish.yml) of how I did it for the [usports-basketball](https://pypi.org/project/usports-basketball/) package. 

> Note: I used `pip` but `poetry` will do the same thing

## **Steps**  
1. Add GitHub as a trusted publisher on PyPI by visiting [PyPI Publishing Settings](https://pypi.org/manage/account/publishing/) (_**you must be logged in**_).
2. Create a GitHub Actions workflow to build and publish the package to PyPI.
3. Use OIDC authentication in the workflow with `id-token: write` permissions.
4. Make sure to trigger only when a new release is published and update version no in `pyproject.toml`. 
```yaml
on:
  release:
    types: [published]
 ```
```toml
[tool.poetry]
name = "mplbasketball"
version = "1.0.0" # update to match release tag. You cant upload the same version twice to pypi
```

<p align="center">
  <img src="https://github.com/user-attachments/assets/bb0679cc-ee02-41bf-bdff-61824e1f31ee" alt="Image 1" width="220" style="margin-right: 20px;" />
  <img src="https://github.com/user-attachments/assets/1169e032-eff2-4e60-8baf-d377a577fdc9" alt="Image 2" width="300" />
</p>
